### ISSUE TITLE
Can we fix the "Each device appears as 4 buttons in HomeKit"?

### ISSUE THREAD

**Issue by alonl** [wibberryd/homebridge-rpi-rts#10]
First, I have to thank you! I followed all the guidelines and it works like charm! You're awesome!!! :)

What is the issue with "Each device appears as 4 buttons in HomeKit..."? 
If I can help with it somehow (contribution to Homebridge?) I'll be happy to get some background before I may dive in...

Thanks again :1st_place_medal:

**Comment by wibberryd** [comment]
Thank you for the message! I am glad it works for you.

About the 4 buttons, it is more a technical limitation than an issue. The RTS technology is one way only: devices do not send any signals back.

It is technically possible to show only one button in HomeKit (the classical Window Covering control with a percentage of opening), and it is easy to code. However, this would be unreliable.

Example:
1) In HomeKit the shutter appears to be closed. We click to open it. Now it appears open.
2) With another remote control, we close the shutter.
3) HomeKit does not know that the shutter is now closed (because the shutter does not send any signals back), and the shutter is still appearing open in HomeKit.

For the moment, I favored reliability over functionality and decided to show 4 buttons (like Somfy remote controls). Like this if we want the shutter to be closed, we press the Down button, and whatever is the current state of the shutter, we know that it will be closed.

However, I will try to propose an experimental version of the plugin with only one button. The main version will probably remain with 4 buttons, but people will be free to try and decide which version they prefer :)
