### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Ryamonster10** [wibberryd/homebridge-rpi-rts#7]
In the default home app, there is a blinds accessory that looks like this:
<img width="200" alt="Picture of blinds accessory in home app" src="https://user-images.githubusercontent.com/45019531/105580402-28548680-5d5a-11eb-8929-ceb2757025c7.png">
I thought it would be nice if that was an option for the plugin.

**Comment by wibberryd** [comment]
Yes, it would be great!

However, unfortunately, there is an important technical limitations in Somfy RTS which would make this impractical: There is no feedback system.

The devices do not send any signal back to the remote. So it is impossible to know the current position of the device.

Of course the plugin could assume that the device is open after sending a 'Up' command, or closed after sending a 'Down' command.

We could even store in the config the average time the device takes to move from open to close, and based on this we could send a 'My' command after a few seconds to be able to stop the device at a specific position: 20%, 50%, 75%, ...

But, if the device was controlled with another remote in-between (the remote on the wall for example), without feedback on the current position, the plugin will be totally lost. Maybe the plugin stored the info that the device is closed, but someone else actually just opened it with another remote. And the plugin will not be able to synchronise with the actual state of the device.

I considered this feature when I was writing the plugin, and I think it would have been much simpler, intuitive and more beautiful like this, unfortunately the RTS technology is too much limited to implement it like this.

This is also probably the reason why the official Somfy box (Tahoma, ...) will never provide HomeKit compatibility for RTS devices, because Apple do not allow to certify a device which do not provide feedback on its current state.

The only way, would be to install Somfy IO devices, which provide feedback on their current state.

**Comment by Ryamonster10** [comment]
What if you replace your exiting wall control with HomeKit compatible buttons (like the Lutron cassata remote control with the corresponding homebridge plugin) that always use the plugin so the plugin can just store the last request and when you look at the blinds accessory, it will just show the position that it was last adjusted to. I know that this may not work for everyone but it would be a nice option (as a config setting). Then each user can time how long it takes for there blinds to reach 100% open and then based on that the plugin could calculated how long it take so you can have precise open and close. Or as an option, if this is impossible or to difficult, you could give the user the choice between conventional switches or a blinds accessory that may not be synced but you can ignore that.

**Comment by wibberryd** [comment]
For info, I have started to work on an experimental version of the plugin exposing a control like this instead of the Up, Down and My buttons. It works, but I need to solve some important bugs before releasing it.

It will probably remain an experimental version, but it will be possible to install it and use it.

I cannot give an estimate for the release date, as I will have a bit less time for this project now, and it depends on how fast or long it will take to solve those bugs, but I will write a message here once it is done.

**Comment by acemtp** [comment]
Just bought a house and play with somfy rts + homebridge + homekit.

Thanks for your plugin, I make it worked (still use the default resonator so the distance is really low, waiting the ebay package).

Seeing 3 accessories for each window is not as smooth as it can be.

I completely understand your point on why you chose that but since I plan to use only homekit to do everything your solution of remembering the last state would be perfect.

If you want alpha tester and/or help on some code, tell me, and in any case thanks for your time!

PS: perhaps you can reopen the issue or create a new one if we want to talk about it.

**Comment by acemtp** [comment]
@wibberryd any news about your experimental version? Would love to check the bug with you and fix them if I can?
