### ISSUE TITLE
Other protocol - enhanced

### ISSUE THREAD

**Issue by phis5533** [wibberryd/homebridge-rpi-rts#9]
Hi,

very great work !

On top of your development, can you add a support for others protocol ? 

I have Somfy awning and it works very well, but I've got Gaposa awning too and I would like to get it into Home App.
It is not a RTS protocol, but called Blinds1/BLINDS_T17 in RFXcom vocabulary.

Do you think it's possible ?

Thanks.
BR,
Philippe

**Comment by wibberryd** [comment]
Hi, and thank you!

**Hardware:**
It seems that Gaposa devices are using 434.15 MHz and 868 MHz for RF communication. The transmitters used in this project are much more basic than RFXcom devices, and are not really able to send signals at different frequencies.

For instance, the usual resonators of 433.92 MHz are already too far from the 433.42 MHz used by Somfy RTS, and it is necessary to change the resonator to get enough range.

I am afraid it would not be possible to control both Somfy RTS and Gaposa devices at the same time with such simple transmitters.

One solution, would be to have two different transmitters, for two different frequencies. As the plugin is not able to handle this for the moment, a solution would be to have one Raspberry Pi connected to a 433.42 MHz transmitter for Somfy RTS, and another Raspberry Pi connected to a 434.15 MHz or 868 MHz transmitter for Gaposa. Each of them with a version of Homebridge running.

**Software:**
The second point is to find how Gaposa RF protocol is working in order to implement it in the code. I was lucky to find a great article detailing the Somfy RTS protocol ([link](https://pushstack.wordpress.com/somfy-rts-protocol/)). After a quick search, I cannot find something similar about Gaposa. Also, I don't have Gaposa devices to perform the tests.

To control both Somfy RTS and Gaposa, maybe the best would be to check RFXcom devices such as RFXtrx433e (check first that it covers all the RF frequencies of your devices). There are already some Homebridge plugin written for them, for example [homebridge-rfxtrx](https://github.com/DaGolle/homebridge-rfxtrx). Also those USB transmitters don't require to give root privilege to Homebridge, so it's a plus for security.

**Comment by phis5533** [comment]
OK, thank you for your complete answer
BR
